### ISSUE TITLE
Need to fix collapsible menu in navigation

### ISSUE THREAD

**Issue by naijenn** [yamalight/generator-powder#5]
After installing, I realized the collapsible version of the menu was not revealing the link/s as it should. The button appears, but nothing happens. 

The following solution worked for me...

Based on a [stackoverflow link](http://stackoverflow.com/questions/23834507/angular-ui-bootstrap-navbar-collapse-and-javascript), modify the navigation/template.html file by replacing the bootstrap native js properties with ui-bootstrap directives (ng-click /collapse)...
```html
<button type="button" class="navbar-toggle" ng-click="navbarCollapsed = !navbarCollapsed">
```
...
```html
<div class="collapse navbar-collapse" collapse="navbarCollapsed">
```
Then update the navigation/controller.js to an initial value of true...
```javascript
function($scope, $location) {
   $scope.navbarCollapsed = true;
```

**Comment by yamalight** [comment]
fixed. thanks for reporting!
